name: encryptscr
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  asn1lib: ^1.5.8
  encrypt: ^5.0.3
  ffi: ^2.1.3
  pointycastle: ^3.9.1
  win32: ^5.8.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
